/**
 * Tool metadata that maps command types to MCP tool definitions.
 * This metadata is combined with TypeScript type information to generate
 * full JSON Schema tool definitions.
 */

import type { CommandType } from '../../types/commands.js';

export interface ToolMetadata {
  /** MCP tool name (e.g., 'figma_create_frame') */
  name: string;
  /** User-facing description of what the tool does */
  description: string;
  /** The command type sent to the Figma plugin */
  commandType: CommandType;
  /** The TypeScript data type name for this command's payload */
  dataType: string;
  /** Required fields for this tool */
  required?: string[];
  /** Whether this is a fetch/query command that returns data */
  isFetchCommand?: boolean;
}

/**
 * Metadata for all Figma tools.
 * Tool definitions are generated by combining this metadata with
 * JSON schemas derived from the TypeScript types.
 */
export const toolMetadata: ToolMetadata[] = [
  // ============ Status ============
  {
    name: 'figma_status',
    description: 'Check if the Figma plugin is connected and ready to receive commands. Call this first if you\'re unsure about connection state.',
    commandType: 'CREATE_PAGE', // Special case - doesn't use a command
    dataType: 'none',
  },

  // ============ Page Operations ============
  {
    name: 'figma_create_page',
    description: 'Create a new page in the Figma file. Pages are top-level containers in Figma documents.',
    commandType: 'CREATE_PAGE',
    dataType: 'PageData',
  },
  {
    name: 'figma_create_page_divider',
    description: 'Create a visual divider in the Figma page list to organize pages into sections.',
    commandType: 'CREATE_PAGE_DIVIDER',
    dataType: 'PageDividerData',
  },

  // ============ Shape Creation ============
  {
    name: 'figma_create_frame',
    description: 'Create a frame container in Figma. Frames are the primary building block for layouts - use them to group elements, create screens, cards, or any container. Enable auto-layout to automatically arrange children horizontally or vertically with consistent spacing.',
    commandType: 'CREATE_FRAME',
    dataType: 'FrameData',
    required: ['name', 'width', 'height'],
  },
  {
    name: 'figma_create_rectangle',
    description: 'Create a rectangle shape. Use for backgrounds, buttons, cards, dividers, or any rectangular element. Unlike frames, rectangles cannot contain children. Use cornerRadius for rounded rectangles.',
    commandType: 'CREATE_RECTANGLE',
    dataType: 'RectangleData',
    required: ['name', 'width', 'height'],
  },
  {
    name: 'figma_create_ellipse',
    description: 'Create an ellipse or circle shape. Set width equal to height for a perfect circle. Use arcData for arcs and pie chart segments.',
    commandType: 'CREATE_ELLIPSE',
    dataType: 'EllipseData',
    required: ['name', 'width', 'height'],
  },
  {
    name: 'figma_create_polygon',
    description: 'Create a regular polygon with a specified number of sides. Use pointCount=3 for triangle, 4 for square/diamond, 5 for pentagon, 6 for hexagon, etc. The polygon fits within the width/height bounds.',
    commandType: 'CREATE_POLYGON',
    dataType: 'PolygonData',
    required: ['pointCount'],
  },
  {
    name: 'figma_create_star',
    description: 'Create a star shape with configurable points and sharpness. Control the star\'s pointiness with innerRadius - lower values create sharper points, higher values create more rounded stars.',
    commandType: 'CREATE_STAR',
    dataType: 'StarData',
    required: ['pointCount'],
  },
  {
    name: 'figma_create_line',
    description: 'Create a line element. Lines are 1-dimensional strokes useful for dividers, separators, or decorative elements. Use dashPattern for dashed/dotted lines. Rotation of 0 = horizontal, 90 = vertical.',
    commandType: 'CREATE_LINE',
    dataType: 'LineData',
    required: ['length'],
  },
  {
    name: 'figma_create_vector',
    description: 'Create a custom vector shape using SVG path commands. Use this for icons, custom shapes, or any path-based artwork. Path data uses standard SVG syntax (M=move, L=line, C=curve, Z=close).',
    commandType: 'CREATE_VECTOR',
    dataType: 'VectorData',
    required: ['vectorPaths'],
  },
  {
    name: 'figma_create_from_svg',
    description: 'Import a complete SVG file as a Figma frame. The SVG is parsed and converted to native Figma vector nodes. Use this for icons, illustrations, or any SVG artwork.',
    commandType: 'CREATE_FROM_SVG',
    dataType: 'SvgImportData',
    required: ['svg'],
  },
  {
    name: 'figma_create_section',
    description: 'Create a section to organize content on the canvas. Sections are high-level containers that visually group related frames and elements. Unlike frames, sections don\'t clip content and are primarily for organization.',
    commandType: 'CREATE_SECTION',
    dataType: 'SectionData',
    required: ['name'],
  },
  {
    name: 'figma_create_slice',
    description: 'Create a slice to define an export region. Slices are invisible guides that mark areas for batch export - useful for exporting specific regions that may span multiple elements.',
    commandType: 'CREATE_SLICE',
    dataType: 'SliceData',
    required: ['width', 'height'],
  },

  // ============ Text ============
  {
    name: 'figma_create_text',
    description: 'Create a text element. The font must be available in Figma - Inter is always safe. Text auto-sizes by default; set width to create a fixed-width text box that wraps.',
    commandType: 'CREATE_TEXT',
    dataType: 'TextData',
    required: ['text'],
  },

  // ============ Components ============
  {
    name: 'figma_create_component',
    description: 'Create a reusable component (master). Components are like templates - create instances to reuse them throughout your design. Changes to a component automatically update all instances. Use \'/\' in names for organization.',
    commandType: 'CREATE_COMPONENT',
    dataType: 'ComponentData',
    required: ['name', 'width', 'height'],
  },
  {
    name: 'figma_create_instance',
    description: 'Create an instance of an existing component. Instances inherit all properties from their master component. You can override specific properties on instances without affecting the master.',
    commandType: 'CREATE_INSTANCE',
    dataType: 'InstanceData',
    required: ['componentId'],
  },

  // ============ Boolean Operations ============
  {
    name: 'figma_boolean_union',
    description: 'Combine multiple shapes into a single merged shape (boolean union/add). All shapes are added together. Useful for creating complex shapes from simpler ones.',
    commandType: 'BOOLEAN_UNION',
    dataType: 'BooleanOperationData',
    required: ['nodeIds'],
  },
  {
    name: 'figma_boolean_subtract',
    description: 'Cut shapes out of the first shape (boolean subtract). The first node in the array is the base shape; all subsequent shapes are subtracted from it.',
    commandType: 'BOOLEAN_SUBTRACT',
    dataType: 'BooleanOperationData',
    required: ['nodeIds'],
  },
  {
    name: 'figma_boolean_intersect',
    description: 'Keep only the overlapping area of shapes (boolean intersect). The result is where all shapes overlap - everything else is removed.',
    commandType: 'BOOLEAN_INTERSECT',
    dataType: 'BooleanOperationData',
    required: ['nodeIds'],
  },
  {
    name: 'figma_boolean_exclude',
    description: 'Remove overlapping areas and keep everything else (boolean exclude/XOR). Where shapes overlap is removed; non-overlapping areas from all shapes are kept.',
    commandType: 'BOOLEAN_EXCLUDE',
    dataType: 'BooleanOperationData',
    required: ['nodeIds'],
  },
  {
    name: 'figma_flatten_node',
    description: 'Flatten a node into a single vector path. Converts complex shapes, groups, or boolean operations into a simple vector.',
    commandType: 'FLATTEN_NODE',
    dataType: 'NodeRefData',
  },

  // ============ Grouping ============
  {
    name: 'figma_group_nodes',
    description: 'Group multiple nodes into a single group container. Groups are simpler than frames - they don\'t have auto-layout or clipping. Use for organizing related elements.',
    commandType: 'GROUP_NODES',
    dataType: 'BooleanOperationData',
    required: ['nodeIds'],
  },
  {
    name: 'figma_ungroup_node',
    description: 'Break apart a group, releasing its children to the parent level. The group container is removed but all children are preserved.',
    commandType: 'UNGROUP_NODE',
    dataType: 'NodeRefData',
  },

  // ============ Styles and Variables ============
  {
    name: 'figma_create_text_style',
    description: 'Create a reusable text style for consistent typography. Text styles define font properties that can be applied to text elements.',
    commandType: 'CREATE_TEXT_STYLE',
    dataType: 'StyleData',
    required: ['name', 'fontSize'],
  },
  {
    name: 'figma_create_color_style',
    description: 'Create a reusable color/paint style. Color styles ensure consistent colors across your design. Apply styles using fillStyleId or strokeStyleId.',
    commandType: 'CREATE_COLOR_STYLE',
    dataType: 'StyleData',
    required: ['name', 'color'],
  },
  {
    name: 'figma_create_effect_style',
    description: 'Create a reusable effect style for consistent shadows and blurs. Effect styles can be applied to elements using effectStyleId.',
    commandType: 'CREATE_EFFECT_STYLE',
    dataType: 'StyleData',
    required: ['name', 'effects'],
  },
  {
    name: 'figma_create_variable_collection',
    description: 'Create a variable collection to organize design tokens. Collections group related variables and support modes (e.g., \'Light\'/\'Dark\' themes).',
    commandType: 'CREATE_VARIABLE_COLLECTION',
    dataType: 'VariableCollectionData',
    required: ['name', 'modes'],
  },
  {
    name: 'figma_create_variable',
    description: 'Create a design token variable in an existing collection. Variables store reusable values (colors, numbers, strings) that can be bound to node properties.',
    commandType: 'CREATE_VARIABLE',
    dataType: 'VariableData',
    required: ['name', 'collectionId', 'resolvedType', 'values'],
  },

  // ============ Modification ============
  {
    name: 'figma_move_node',
    description: 'Move a node to a new position on the canvas. Position is ignored for nodes inside auto-layout parents.',
    commandType: 'MOVE_NODE',
    dataType: 'MoveNodeData',
  },
  {
    name: 'figma_update_node',
    description: 'Update properties of an existing node. Modify any visual property - size, position, colors, strokes, visibility, etc. Only specify properties you want to change.',
    commandType: 'UPDATE_NODE',
    dataType: 'UpdateNodeData',
  },
  {
    name: 'figma_delete_node',
    description: 'Permanently delete a node and all its children. This cannot be undone via the API.',
    commandType: 'DELETE_NODE',
    dataType: 'NodeRefData',
  },
  {
    name: 'figma_set_constraints',
    description: 'Set how a node behaves when its parent frame is resized. Constraints control pinning and scaling behavior.',
    commandType: 'SET_CONSTRAINTS',
    dataType: 'SetConstraintsData',
    required: ['horizontal', 'vertical'],
  },
  {
    name: 'figma_set_layout_grids',
    description: 'Add layout grids to a frame for visual alignment guides. Grids help with consistent spacing and alignment.',
    commandType: 'SET_LAYOUT_GRIDS',
    dataType: 'SetLayoutGridsData',
    required: ['layoutGrids'],
  },
  {
    name: 'figma_set_effects',
    description: 'Apply visual effects like shadows and blurs to a node. Multiple effects can be stacked.',
    commandType: 'SET_EFFECTS',
    dataType: 'SetEffectsData',
    required: ['effects'],
  },
  {
    name: 'figma_set_blend_mode',
    description: 'Set how a node blends with elements behind it. Common modes: NORMAL (default), MULTIPLY (darken), SCREEN (lighten), OVERLAY (contrast).',
    commandType: 'SET_BLEND_MODE',
    dataType: 'SetBlendModeData',
    required: ['blendMode'],
  },
  {
    name: 'figma_set_gradient_fill',
    description: 'Apply a gradient fill to a node. LINEAR for directional gradients, RADIAL for circular/oval gradients, ANGULAR for sweep gradients, DIAMOND for four-way gradients.',
    commandType: 'SET_GRADIENT_FILL',
    dataType: 'SetGradientFillData',
    required: ['type', 'gradientStops'],
  },

  // ============ Viewport and Selection ============
  {
    name: 'figma_set_selection',
    description: 'Programmatically select nodes in Figma. Updates what the user sees selected in the canvas and layers panel.',
    commandType: 'SET_SELECTION',
    dataType: 'SetSelectionData',
    required: ['nodeIds'],
  },
  {
    name: 'figma_zoom_to_fit',
    description: 'Pan and zoom the viewport to frame specific nodes. Useful after creating content to show it to the user.',
    commandType: 'ZOOM_TO_FIT',
    dataType: 'NodeRefData',
  },
  {
    name: 'figma_get_viewport',
    description: 'Get the current viewport state - what area of the canvas the user is viewing. Returns center position and zoom level.',
    commandType: 'GET_VIEWPORT',
    dataType: 'undefined',
    isFetchCommand: true,
  },
  {
    name: 'figma_set_viewport',
    description: 'Set the viewport to a specific position and zoom level. Use to navigate the user to a specific canvas area.',
    commandType: 'SET_VIEWPORT',
    dataType: 'ViewportData',
  },

  // ============ Queries ============
  {
    name: 'figma_get_node_by_name',
    description: 'Find a node by its name in the layers panel. Returns the first match. Optionally register it for later reference.',
    commandType: 'GET_NODE_BY_NAME',
    dataType: 'NodeRefData',
    required: ['name'],
    isFetchCommand: true,
  },
  {
    name: 'figma_get_selection',
    description: 'Get details about what the user has selected in Figma. Useful for understanding context or operating on user-selected elements.',
    commandType: 'GET_SELECTION',
    dataType: 'QueryData',
    isFetchCommand: true,
  },
  {
    name: 'figma_get_page_nodes',
    description: 'Get an overview of all top-level nodes on the current Figma page. Use this to understand what\'s on the canvas.',
    commandType: 'GET_PAGE_NODES',
    dataType: 'QueryData',
    isFetchCommand: true,
  },
  {
    name: 'figma_get_node_by_id',
    description: 'Fetch detailed information about a specific node using its Figma ID. Returns full properties including fills, strokes, effects, and children.',
    commandType: 'GET_NODE_BY_ID',
    dataType: 'NodeRefData',
    required: ['nodeId'],
    isFetchCommand: true,
  },
  {
    name: 'figma_find_nodes',
    description: 'Search for nodes matching criteria. Supports partial name matching (case-insensitive) and type filtering. Returns multiple matches.',
    commandType: 'FIND_NODES',
    dataType: 'FindNodesData',
    isFetchCommand: true,
  },
  {
    name: 'figma_get_styles',
    description: 'List all local styles defined in the document. Styles are reusable design tokens for colors, typography, and effects.',
    commandType: 'GET_STYLES',
    dataType: 'QueryData',
    isFetchCommand: true,
  },
  {
    name: 'figma_get_components',
    description: 'List all local components (masters) in the document. Use this to discover available reusable components before creating instances.',
    commandType: 'GET_COMPONENTS',
    dataType: 'QueryData',
    isFetchCommand: true,
  },
  {
    name: 'figma_get_variables',
    description: 'List all variable collections and their variables (design tokens). Variables store reusable values like colors, spacing, and strings.',
    commandType: 'GET_VARIABLES',
    dataType: 'undefined',
    isFetchCommand: true,
  },

  // ============ Import ============
  {
    name: 'figma_import_component',
    description: 'Import a component from a library by its key. The component is fetched from the Figma library and registered for use. Use the returned registryId to create instances of this component.',
    commandType: 'IMPORT_COMPONENT',
    dataType: 'ImportComponentData',
    required: ['key'],
  },

  // ============ Export ============
  {
    name: 'figma_export_node',
    description: 'Export a node to an image format or JSON. PNG/JPG/SVG return base64-encoded data. JSON returns the node\'s serialized properties.',
    commandType: 'EXPORT_NODE',
    dataType: 'ExportNodeData',
    isFetchCommand: true,
  },
];

/**
 * Map from tool name to metadata for quick lookup
 */
export const toolMetadataByName = new Map(
  toolMetadata.map((m) => [m.name, m])
);

/**
 * Map from command type to tool name for quick lookup
 */
export const toolNameByCommandType = new Map(
  toolMetadata.map((m) => [m.commandType, m.name])
);

/**
 * Set of command types that return data (fetch/query commands)
 */
export const fetchCommandTypes = new Set(
  toolMetadata.filter((m) => m.isFetchCommand).map((m) => m.commandType)
);
